[project]
name = "tinygpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "metriiics", email = "metriics@yandex.ru" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "git-filter-repo>=2.47.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "python-multipart>=0.0.32",
    "tiktoken>=0.14.0",
    "tokenizers>=0.23.2",
    "torch>=2.11.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
tinygpt = "main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128"

[tool.uv]
package = false
